language: python

python:
  - "3.5"

install:
  # up-to-date pip
  - pip install --upgrade pip

  # package dependencies
  - pip install -r requirements.txt

  # test dependencies
  - pip install codecov

script:
  - "./.travis/test.sh"

notifications:
  email: false

